name: Caliper Test
version: "2.0.0"

caliper:
  blockchain: fabric

channels:
  - channelName: channel1
    contracts:
      - id: chaincode-go

organizations:
  - mspid: peer-msp
    identities:
      certificates:
        - name: "user1"
          clientPrivateKey:
            path: /opt/gopath/src/caliper-workspace/peer-client.key
          clientSignedCert:
            path: /opt/gopath/src/caliper-workspace/peer-client.pem
    connectionProfile:
      path: /opt/gopath/src/caliper-workspace/connection_property_peer-msp.json
